#![doc = "Peripheral access API for ASR6601 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn SEC();
    fn RTC();
    fn WWDG();
    fn EFC();
    fn UART3();
    fn I2C2();
    fn UART0();
    fn UART1();
    fn UART2();
    fn LPUART();
    fn SSP0();
    fn SSP1();
    fn QSPI();
    fn I2C0();
    fn I2C1();
    fn ADC();
    fn AFEC();
    fn SSP2();
    fn DMAC1();
    fn DAC();
    fn LORA();
    fn GPIO();
    fn GPTIM0();
    fn GPTIM1();
    fn GPTIM2();
    fn GPTIM3();
    fn BSTIM0();
    fn BSTIM1();
    fn LPTIM0();
    fn SAC();
    fn DMAC0();
    fn I2S();
    fn LCD();
    fn PWR();
    fn LPTIM1();
    fn IWDG();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 37] = [
    Vector { _handler: SEC },
    Vector { _handler: RTC },
    Vector { _handler: WWDG },
    Vector { _handler: EFC },
    Vector { _handler: UART3 },
    Vector { _handler: I2C2 },
    Vector { _handler: UART0 },
    Vector { _handler: UART1 },
    Vector { _handler: UART2 },
    Vector { _handler: LPUART },
    Vector { _handler: SSP0 },
    Vector { _handler: SSP1 },
    Vector { _handler: QSPI },
    Vector { _handler: I2C0 },
    Vector { _handler: I2C1 },
    Vector { _reserved: 0 },
    Vector { _handler: ADC },
    Vector { _handler: AFEC },
    Vector { _handler: SSP2 },
    Vector { _handler: DMAC1 },
    Vector { _handler: DAC },
    Vector { _handler: LORA },
    Vector { _handler: GPIO },
    Vector { _handler: GPTIM0 },
    Vector { _handler: GPTIM1 },
    Vector { _handler: GPTIM2 },
    Vector { _handler: GPTIM3 },
    Vector { _handler: BSTIM0 },
    Vector { _handler: BSTIM1 },
    Vector { _handler: LPTIM0 },
    Vector { _handler: SAC },
    Vector { _handler: DMAC0 },
    Vector { _handler: I2S },
    Vector { _handler: LCD },
    Vector { _handler: PWR },
    Vector { _handler: LPTIM1 },
    Vector { _handler: IWDG },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - SEC"]
    SEC = 0,
    #[doc = "1 - RTC"]
    RTC = 1,
    #[doc = "2 - WWDG"]
    WWDG = 2,
    #[doc = "3 - EFC"]
    EFC = 3,
    #[doc = "4 - UART3"]
    UART3 = 4,
    #[doc = "5 - I2C2"]
    I2C2 = 5,
    #[doc = "6 - UART0"]
    UART0 = 6,
    #[doc = "7 - UART1"]
    UART1 = 7,
    #[doc = "8 - UART2"]
    UART2 = 8,
    #[doc = "9 - LPUART"]
    LPUART = 9,
    #[doc = "10 - SSP0"]
    SSP0 = 10,
    #[doc = "11 - SSP1"]
    SSP1 = 11,
    #[doc = "12 - QSPI"]
    QSPI = 12,
    #[doc = "13 - I2C0"]
    I2C0 = 13,
    #[doc = "14 - I2C1"]
    I2C1 = 14,
    #[doc = "16 - ADC"]
    ADC = 16,
    #[doc = "17 - AFEC"]
    AFEC = 17,
    #[doc = "18 - SSP2"]
    SSP2 = 18,
    #[doc = "19 - DMAC1"]
    DMAC1 = 19,
    #[doc = "20 - DAC"]
    DAC = 20,
    #[doc = "21 - LORA"]
    LORA = 21,
    #[doc = "22 - GPIO"]
    GPIO = 22,
    #[doc = "23 - GPTIM0"]
    GPTIM0 = 23,
    #[doc = "24 - GPTIM1"]
    GPTIM1 = 24,
    #[doc = "25 - GPTIM2"]
    GPTIM2 = 25,
    #[doc = "26 - GPTIM3"]
    GPTIM3 = 26,
    #[doc = "27 - BSTIM0"]
    BSTIM0 = 27,
    #[doc = "28 - BSTIM1"]
    BSTIM1 = 28,
    #[doc = "29 - LPTIM0"]
    LPTIM0 = 29,
    #[doc = "30 - SDK SAC interrupt vector; SDK does not state MMIO ownership"]
    SAC = 30,
    #[doc = "31 - DMAC0"]
    DMAC0 = 31,
    #[doc = "32 - I2S"]
    I2S = 32,
    #[doc = "33 - LCD"]
    LCD = 33,
    #[doc = "34 - PWR"]
    PWR = 34,
    #[doc = "35 - LPTIM1"]
    LPTIM1 = 35,
    #[doc = "36 - IWDG"]
    IWDG = 36,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Reset and clock control"]
pub type Rcc = crate::Periph<rcc::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Rcc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rcc").finish()
    }
}
#[doc = "Reset and clock control"]
pub mod rcc;
#[doc = "System configuration controller"]
pub type Syscfg = crate::Periph<syscfg::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Syscfg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Syscfg").finish()
    }
}
#[doc = "System configuration controller"]
pub mod syscfg;
#[doc = "Power controller"]
pub type Pwr = crate::Periph<pwr::RegisterBlock, 0x4000_1800>;
impl core::fmt::Debug for Pwr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwr").finish()
    }
}
#[doc = "Power controller"]
pub mod pwr;
#[doc = "Inter-IC sound interface"]
pub type I2s = crate::Periph<i2s::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for I2s {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s").finish()
    }
}
#[doc = "Inter-IC sound interface"]
pub mod i2s;
#[doc = "Uart0"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "Uart0"]
pub mod uart0;
#[doc = "UART1 instance"]
pub type Uart1 = crate::Periph<uart0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "UART1 instance"]
pub use self::uart0 as uart1;
#[doc = "Low-power UART"]
pub type Lpuart = crate::Periph<lpuart::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Lpuart {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpuart").finish()
    }
}
#[doc = "Low-power UART"]
pub mod lpuart;
#[doc = "Ssp0"]
pub type Ssp0 = crate::Periph<ssp0::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Ssp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ssp0").finish()
    }
}
#[doc = "Ssp0"]
pub mod ssp0;
#[doc = "I2c0"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "I2c0"]
pub mod i2c0;
#[doc = "Analog front-end controller digital registers"]
pub type Afec = crate::Periph<afec::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Afec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Afec").finish()
    }
}
#[doc = "Analog front-end controller digital registers"]
pub mod afec;
#[doc = "LoRa controller interface"]
pub type Lorac = crate::Periph<lorac::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Lorac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lorac").finish()
    }
}
#[doc = "LoRa controller interface"]
pub mod lorac;
#[doc = "Gptim0"]
pub type Gptim0 = crate::Periph<gptim0::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Gptim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gptim0").finish()
    }
}
#[doc = "Gptim0"]
pub mod gptim0;
#[doc = "GPTIM2 instance"]
pub type Gptim2 = crate::Periph<gptim0::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Gptim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gptim2").finish()
    }
}
#[doc = "GPTIM2 instance"]
pub use self::gptim0 as gptim2;
#[doc = "Bstim0"]
pub type Bstim0 = crate::Periph<bstim0::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Bstim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bstim0").finish()
    }
}
#[doc = "Bstim0"]
pub mod bstim0;
#[doc = "Lptim0"]
pub type Lptim0 = crate::Periph<lptim0::RegisterBlock, 0x4000_d000>;
impl core::fmt::Debug for Lptim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lptim0").finish()
    }
}
#[doc = "Lptim0"]
pub mod lptim0;
#[doc = "LPTIM1 instance"]
pub type Lptim1 = crate::Periph<lptim0::RegisterBlock, 0x4000_d800>;
impl core::fmt::Debug for Lptim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lptim1").finish()
    }
}
#[doc = "LPTIM1 instance"]
pub use self::lptim0 as lptim1;
#[doc = "Real-time clock"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "Real-time clock"]
pub mod rtc;
#[doc = "Security controller"]
pub type Sec = crate::Periph<sec::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Sec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sec").finish()
    }
}
#[doc = "Security controller"]
pub mod sec;
#[doc = "UART2 instance"]
pub type Uart2 = crate::Periph<uart0::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "UART2 instance"]
pub use self::uart0 as uart2;
#[doc = "UART3 instance"]
pub type Uart3 = crate::Periph<uart0::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Uart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart3").finish()
    }
}
#[doc = "UART3 instance"]
pub use self::uart0 as uart3;
#[doc = "SSP1 instance"]
pub type Ssp1 = crate::Periph<ssp0::RegisterBlock, 0x4001_2000>;
impl core::fmt::Debug for Ssp1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ssp1").finish()
    }
}
#[doc = "SSP1 instance"]
pub use self::ssp0 as ssp1;
#[doc = "SSP2 instance"]
pub type Ssp2 = crate::Periph<ssp0::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Ssp2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ssp2").finish()
    }
}
#[doc = "SSP2 instance"]
pub use self::ssp0 as ssp2;
#[doc = "I2C1 instance"]
pub type I2c1 = crate::Periph<i2c0::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "I2C1 instance"]
pub use self::i2c0 as i2c1;
#[doc = "I2C2 instance"]
pub type I2c2 = crate::Periph<i2c0::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "I2C2 instance"]
pub use self::i2c0 as i2c2;
#[doc = "12-bit analog-to-digital converter"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4001_7000>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "12-bit analog-to-digital converter"]
pub mod adc;
#[doc = "Segment LCD controller"]
pub type Lcd = crate::Periph<lcd::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Lcd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lcd").finish()
    }
}
#[doc = "Segment LCD controller"]
pub mod lcd;
#[doc = "12-bit digital-to-analog converter"]
pub type Dac = crate::Periph<dac::RegisterBlock, 0x4001_9000>;
impl core::fmt::Debug for Dac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac").finish()
    }
}
#[doc = "12-bit digital-to-analog converter"]
pub mod dac;
#[doc = "GPTIM1 instance"]
pub type Gptim1 = crate::Periph<gptim0::RegisterBlock, 0x4001_a000>;
impl core::fmt::Debug for Gptim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gptim1").finish()
    }
}
#[doc = "GPTIM1 instance"]
pub use self::gptim0 as gptim1;
#[doc = "GPTIM3 instance"]
pub type Gptim3 = crate::Periph<gptim0::RegisterBlock, 0x4001_b000>;
impl core::fmt::Debug for Gptim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gptim3").finish()
    }
}
#[doc = "GPTIM3 instance"]
pub use self::gptim0 as gptim3;
#[doc = "BSTIM1 instance"]
pub type Bstim1 = crate::Periph<bstim0::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Bstim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bstim1").finish()
    }
}
#[doc = "BSTIM1 instance"]
pub use self::bstim0 as bstim1;
#[doc = "Independent watchdog"]
pub type Iwdg = crate::Periph<iwdg::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Iwdg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iwdg").finish()
    }
}
#[doc = "Independent watchdog"]
pub mod iwdg;
#[doc = "Window watchdog timer"]
pub type Wwdg = crate::Periph<wwdg::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for Wwdg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdg").finish()
    }
}
#[doc = "Window watchdog timer"]
pub mod wwdg;
#[doc = "Gpioa"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "Gpioa"]
pub mod gpioa;
#[doc = "GPIOB instance"]
pub type Gpiob = crate::Periph<gpioa::RegisterBlock, 0x4001_f400>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "GPIOB instance"]
pub use self::gpioa as gpiob;
#[doc = "GPIOC instance"]
pub type Gpioc = crate::Periph<gpioa::RegisterBlock, 0x4001_f800>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "GPIOC instance"]
pub use self::gpioa as gpioc;
#[doc = "Gpioa"]
pub type Gpiod = crate::Periph<gpiod::RegisterBlock, 0x4001_fc00>;
impl core::fmt::Debug for Gpiod {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiod").finish()
    }
}
#[doc = "Gpioa"]
pub mod gpiod;
#[doc = "Embedded flash controller"]
pub type Efc = crate::Periph<efc::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Efc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Efc").finish()
    }
}
#[doc = "Embedded flash controller"]
pub mod efc;
#[doc = "Quad SPI controller"]
pub type Qspi = crate::Periph<qspi::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Qspi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qspi").finish()
    }
}
#[doc = "Quad SPI controller"]
pub mod qspi;
#[doc = "CRC calculation unit"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC calculation unit"]
pub mod crc;
#[doc = "DMA Controller 0"]
pub type Dmac0 = crate::Periph<dmac0::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Dmac0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac0").finish()
    }
}
#[doc = "DMA Controller 0"]
pub mod dmac0;
#[doc = "DMAC1 instance"]
pub type Dmac1 = crate::Periph<dmac0::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for Dmac1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmac1").finish()
    }
}
#[doc = "DMAC1 instance"]
pub use self::dmac0 as dmac1;
#[doc = "Security algorithm engine"]
pub type Sac = crate::Periph<sac::RegisterBlock, 0x4003_2000>;
impl core::fmt::Debug for Sac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sac").finish()
    }
}
#[doc = "Security algorithm engine"]
pub mod sac;
#[doc = "Hardware random-number generator"]
pub type Rngc = crate::Periph<rngc::RegisterBlock, 0x4003_3000>;
impl core::fmt::Debug for Rngc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rngc").finish()
    }
}
#[doc = "Hardware random-number generator"]
pub mod rngc;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "RCC"]
    pub rcc: Rcc,
    #[doc = "SYSCFG"]
    pub syscfg: Syscfg,
    #[doc = "PWR"]
    pub pwr: Pwr,
    #[doc = "I2S"]
    pub i2s: I2s,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "LPUART"]
    pub lpuart: Lpuart,
    #[doc = "SSP0"]
    pub ssp0: Ssp0,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "AFEC"]
    pub afec: Afec,
    #[doc = "LORAC"]
    pub lorac: Lorac,
    #[doc = "GPTIM0"]
    pub gptim0: Gptim0,
    #[doc = "GPTIM2"]
    pub gptim2: Gptim2,
    #[doc = "BSTIM0"]
    pub bstim0: Bstim0,
    #[doc = "LPTIM0"]
    pub lptim0: Lptim0,
    #[doc = "LPTIM1"]
    pub lptim1: Lptim1,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SEC"]
    pub sec: Sec,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "UART3"]
    pub uart3: Uart3,
    #[doc = "SSP1"]
    pub ssp1: Ssp1,
    #[doc = "SSP2"]
    pub ssp2: Ssp2,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "LCD"]
    pub lcd: Lcd,
    #[doc = "DAC"]
    pub dac: Dac,
    #[doc = "GPTIM1"]
    pub gptim1: Gptim1,
    #[doc = "GPTIM3"]
    pub gptim3: Gptim3,
    #[doc = "BSTIM1"]
    pub bstim1: Bstim1,
    #[doc = "IWDG"]
    pub iwdg: Iwdg,
    #[doc = "WWDG"]
    pub wwdg: Wwdg,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "GPIOD"]
    pub gpiod: Gpiod,
    #[doc = "EFC"]
    pub efc: Efc,
    #[doc = "QSPI"]
    pub qspi: Qspi,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "DMAC0"]
    pub dmac0: Dmac0,
    #[doc = "DMAC1"]
    pub dmac1: Dmac1,
    #[doc = "SAC"]
    pub sac: Sac,
    #[doc = "RNGC"]
    pub rngc: Rngc,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            rcc: Rcc::steal(),
            syscfg: Syscfg::steal(),
            pwr: Pwr::steal(),
            i2s: I2s::steal(),
            uart0: Uart0::steal(),
            uart1: Uart1::steal(),
            lpuart: Lpuart::steal(),
            ssp0: Ssp0::steal(),
            i2c0: I2c0::steal(),
            afec: Afec::steal(),
            lorac: Lorac::steal(),
            gptim0: Gptim0::steal(),
            gptim2: Gptim2::steal(),
            bstim0: Bstim0::steal(),
            lptim0: Lptim0::steal(),
            lptim1: Lptim1::steal(),
            rtc: Rtc::steal(),
            sec: Sec::steal(),
            uart2: Uart2::steal(),
            uart3: Uart3::steal(),
            ssp1: Ssp1::steal(),
            ssp2: Ssp2::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            adc: Adc::steal(),
            lcd: Lcd::steal(),
            dac: Dac::steal(),
            gptim1: Gptim1::steal(),
            gptim3: Gptim3::steal(),
            bstim1: Bstim1::steal(),
            iwdg: Iwdg::steal(),
            wwdg: Wwdg::steal(),
            gpioa: Gpioa::steal(),
            gpiob: Gpiob::steal(),
            gpioc: Gpioc::steal(),
            gpiod: Gpiod::steal(),
            efc: Efc::steal(),
            qspi: Qspi::steal(),
            crc: Crc::steal(),
            dmac0: Dmac0::steal(),
            dmac1: Dmac1::steal(),
            sac: Sac::steal(),
            rngc: Rngc::steal(),
        }
    }
}
