#![doc = "Peripheral access API for ASR6601 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn SEC();
    fn RTC();
    fn WDG();
    fn EFC();
    fn UART3();
    fn I2C2();
    fn UART0();
    fn UART1();
    fn UART2();
    fn LPUART();
    fn SSP0();
    fn SSP1();
    fn QSPI();
    fn I2C0();
    fn I2C1();
    fn SCC();
    fn ADC();
    fn AFEC();
    fn SSP2();
    fn DMA1();
    fn DAC();
    fn LORA();
    fn GPIO();
    fn TIMER0();
    fn TIMER1();
    fn TIMER2();
    fn TIMER3();
    fn BSTIMER0();
    fn BSTIMER1();
    fn LPTIMER0();
    fn SAC();
    fn DMA0();
    fn I2S();
    fn LCD();
    fn PWR();
    fn LPTIMER1();
    fn IWDG();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 37] = [
    Vector { _handler: SEC },
    Vector { _handler: RTC },
    Vector { _handler: WDG },
    Vector { _handler: EFC },
    Vector { _handler: UART3 },
    Vector { _handler: I2C2 },
    Vector { _handler: UART0 },
    Vector { _handler: UART1 },
    Vector { _handler: UART2 },
    Vector { _handler: LPUART },
    Vector { _handler: SSP0 },
    Vector { _handler: SSP1 },
    Vector { _handler: QSPI },
    Vector { _handler: I2C0 },
    Vector { _handler: I2C1 },
    Vector { _handler: SCC },
    Vector { _handler: ADC },
    Vector { _handler: AFEC },
    Vector { _handler: SSP2 },
    Vector { _handler: DMA1 },
    Vector { _handler: DAC },
    Vector { _handler: LORA },
    Vector { _handler: GPIO },
    Vector { _handler: TIMER0 },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _handler: TIMER3 },
    Vector { _handler: BSTIMER0 },
    Vector { _handler: BSTIMER1 },
    Vector { _handler: LPTIMER0 },
    Vector { _handler: SAC },
    Vector { _handler: DMA0 },
    Vector { _handler: I2S },
    Vector { _handler: LCD },
    Vector { _handler: PWR },
    Vector { _handler: LPTIMER1 },
    Vector { _handler: IWDG },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - SEC"]
    SEC = 0,
    #[doc = "1 - RTC"]
    RTC = 1,
    #[doc = "2 - WDG"]
    WDG = 2,
    #[doc = "3 - EFC"]
    EFC = 3,
    #[doc = "4 - UART3"]
    UART3 = 4,
    #[doc = "5 - I2C2"]
    I2C2 = 5,
    #[doc = "6 - UART0"]
    UART0 = 6,
    #[doc = "7 - UART1"]
    UART1 = 7,
    #[doc = "8 - UART2"]
    UART2 = 8,
    #[doc = "9 - LPUART"]
    LPUART = 9,
    #[doc = "10 - SSP0"]
    SSP0 = 10,
    #[doc = "11 - SSP1"]
    SSP1 = 11,
    #[doc = "12 - QSPI"]
    QSPI = 12,
    #[doc = "13 - I2C0"]
    I2C0 = 13,
    #[doc = "14 - I2C1"]
    I2C1 = 14,
    #[doc = "15 - SDK SCC interrupt vector; SDK does not publish an SCC MMIO base"]
    SCC = 15,
    #[doc = "16 - ADC"]
    ADC = 16,
    #[doc = "17 - AFEC"]
    AFEC = 17,
    #[doc = "18 - SSP2"]
    SSP2 = 18,
    #[doc = "19 - DMA1"]
    DMA1 = 19,
    #[doc = "20 - DAC"]
    DAC = 20,
    #[doc = "21 - LORA"]
    LORA = 21,
    #[doc = "22 - GPIO"]
    GPIO = 22,
    #[doc = "23 - TIMER0"]
    TIMER0 = 23,
    #[doc = "24 - TIMER1"]
    TIMER1 = 24,
    #[doc = "25 - TIMER2"]
    TIMER2 = 25,
    #[doc = "26 - TIMER3"]
    TIMER3 = 26,
    #[doc = "27 - BSTIMER0"]
    BSTIMER0 = 27,
    #[doc = "28 - BSTIMER1"]
    BSTIMER1 = 28,
    #[doc = "29 - LPTIMER0"]
    LPTIMER0 = 29,
    #[doc = "30 - SDK SAC interrupt vector; SDK does not state MMIO ownership"]
    SAC = 30,
    #[doc = "31 - DMA0"]
    DMA0 = 31,
    #[doc = "32 - I2S"]
    I2S = 32,
    #[doc = "33 - LCD"]
    LCD = 33,
    #[doc = "34 - PWR"]
    PWR = 34,
    #[doc = "35 - LPTIMER1"]
    LPTIMER1 = 35,
    #[doc = "36 - IWDG"]
    IWDG = 36,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Reset and clock control"]
pub type Rcc = crate::Periph<rcc::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Rcc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rcc").finish()
    }
}
#[doc = "Reset and clock control"]
pub mod rcc;
#[doc = "System configuration controller"]
pub type Syscfg = crate::Periph<syscfg::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Syscfg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Syscfg").finish()
    }
}
#[doc = "System configuration controller"]
pub mod syscfg;
#[doc = "Power controller"]
pub type Pwr = crate::Periph<pwr::RegisterBlock, 0x4000_1800>;
impl core::fmt::Debug for Pwr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwr").finish()
    }
}
#[doc = "Power controller"]
pub mod pwr;
#[doc = "Inter-IC sound interface"]
pub type I2s = crate::Periph<i2s::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for I2s {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s").finish()
    }
}
#[doc = "Inter-IC sound interface"]
pub mod i2s;
#[doc = "Uart0"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "Uart0"]
pub mod uart0;
#[doc = "UART1 instance"]
pub type Uart1 = crate::Periph<uart0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "UART1 instance"]
pub use self::uart0 as uart1;
#[doc = "Low-power UART"]
pub type Lpuart = crate::Periph<lpuart::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Lpuart {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpuart").finish()
    }
}
#[doc = "Low-power UART"]
pub mod lpuart;
#[doc = "Ssp0"]
pub type Ssp0 = crate::Periph<ssp0::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Ssp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ssp0").finish()
    }
}
#[doc = "Ssp0"]
pub mod ssp0;
#[doc = "I2c0"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "I2c0"]
pub mod i2c0;
#[doc = "Analog front-end controller digital registers"]
pub type Afec = crate::Periph<afec::RegisterBlock, 0x4000_8200>;
impl core::fmt::Debug for Afec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Afec").finish()
    }
}
#[doc = "Analog front-end controller digital registers"]
pub mod afec;
#[doc = "LoRa controller interface"]
pub type Lorac = crate::Periph<lorac::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Lorac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lorac").finish()
    }
}
#[doc = "LoRa controller interface"]
pub mod lorac;
#[doc = "Timer0"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "Timer0"]
pub mod timer0;
#[doc = "TIMER2 instance"]
pub type Timer2 = crate::Periph<timer0::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Timer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2").finish()
    }
}
#[doc = "TIMER2 instance"]
pub use self::timer0 as timer2;
#[doc = "Bstimer0"]
pub type Bstimer0 = crate::Periph<bstimer0::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Bstimer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bstimer0").finish()
    }
}
#[doc = "Bstimer0"]
pub mod bstimer0;
#[doc = "Lptimer0"]
pub type Lptimer0 = crate::Periph<lptimer0::RegisterBlock, 0x4000_d000>;
impl core::fmt::Debug for Lptimer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lptimer0").finish()
    }
}
#[doc = "Lptimer0"]
pub mod lptimer0;
#[doc = "LPTIMER1 instance"]
pub type Lptimer1 = crate::Periph<lptimer0::RegisterBlock, 0x4000_d800>;
impl core::fmt::Debug for Lptimer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lptimer1").finish()
    }
}
#[doc = "LPTIMER1 instance"]
pub use self::lptimer0 as lptimer1;
#[doc = "Real-time clock"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "Real-time clock"]
pub mod rtc;
#[doc = "Security controller"]
pub type Sec = crate::Periph<sec::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Sec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sec").finish()
    }
}
#[doc = "Security controller"]
pub mod sec;
#[doc = "UART2 instance"]
pub type Uart2 = crate::Periph<uart0::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "UART2 instance"]
pub use self::uart0 as uart2;
#[doc = "UART3 instance"]
pub type Uart3 = crate::Periph<uart0::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Uart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart3").finish()
    }
}
#[doc = "UART3 instance"]
pub use self::uart0 as uart3;
#[doc = "SSP1 instance"]
pub type Ssp1 = crate::Periph<ssp0::RegisterBlock, 0x4001_2000>;
impl core::fmt::Debug for Ssp1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ssp1").finish()
    }
}
#[doc = "SSP1 instance"]
pub use self::ssp0 as ssp1;
#[doc = "SSP2 instance"]
pub type Ssp2 = crate::Periph<ssp0::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Ssp2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ssp2").finish()
    }
}
#[doc = "SSP2 instance"]
pub use self::ssp0 as ssp2;
#[doc = "I2C1 instance"]
pub type I2c1 = crate::Periph<i2c0::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "I2C1 instance"]
pub use self::i2c0 as i2c1;
#[doc = "I2C2 instance"]
pub type I2c2 = crate::Periph<i2c0::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "I2C2 instance"]
pub use self::i2c0 as i2c2;
#[doc = "12-bit analog-to-digital converter"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4001_7000>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "12-bit analog-to-digital converter"]
pub mod adc;
#[doc = "Segment LCD controller"]
pub type Lcd = crate::Periph<lcd::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Lcd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lcd").finish()
    }
}
#[doc = "Segment LCD controller"]
pub mod lcd;
#[doc = "12-bit digital-to-analog converter"]
pub type Dac = crate::Periph<dac::RegisterBlock, 0x4001_9000>;
impl core::fmt::Debug for Dac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac").finish()
    }
}
#[doc = "12-bit digital-to-analog converter"]
pub mod dac;
#[doc = "TIMER1 instance"]
pub type Timer1 = crate::Periph<timer0::RegisterBlock, 0x4001_a000>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
#[doc = "TIMER1 instance"]
pub use self::timer0 as timer1;
#[doc = "TIMER3 instance"]
pub type Timer3 = crate::Periph<timer0::RegisterBlock, 0x4001_b000>;
impl core::fmt::Debug for Timer3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer3").finish()
    }
}
#[doc = "TIMER3 instance"]
pub use self::timer0 as timer3;
#[doc = "BSTIMER1 instance"]
pub type Bstimer1 = crate::Periph<bstimer0::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Bstimer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bstimer1").finish()
    }
}
#[doc = "BSTIMER1 instance"]
pub use self::bstimer0 as bstimer1;
#[doc = "Independent watchdog"]
pub type Iwdg = crate::Periph<iwdg::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Iwdg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iwdg").finish()
    }
}
#[doc = "Independent watchdog"]
pub mod iwdg;
#[doc = "Watchdog timer"]
pub type Wdg = crate::Periph<wdg::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for Wdg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdg").finish()
    }
}
#[doc = "Watchdog timer"]
pub mod wdg;
#[doc = "Gpioa"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "Gpioa"]
pub mod gpioa;
#[doc = "GPIOB instance"]
pub type Gpiob = crate::Periph<gpioa::RegisterBlock, 0x4001_f400>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "GPIOB instance"]
pub use self::gpioa as gpiob;
#[doc = "GPIOC instance"]
pub type Gpioc = crate::Periph<gpioa::RegisterBlock, 0x4001_f800>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "GPIOC instance"]
pub use self::gpioa as gpioc;
#[doc = "Gpioa"]
pub type Gpiod = crate::Periph<gpiod::RegisterBlock, 0x4001_fc00>;
impl core::fmt::Debug for Gpiod {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiod").finish()
    }
}
#[doc = "Gpioa"]
pub mod gpiod;
#[doc = "Embedded flash controller"]
pub type Efc = crate::Periph<efc::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Efc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Efc").finish()
    }
}
#[doc = "Embedded flash controller"]
pub mod efc;
#[doc = "CRC calculation unit"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC calculation unit"]
pub mod crc;
#[doc = "DMA Controller 0"]
pub type Dma0 = crate::Periph<dma0::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Dma0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma0").finish()
    }
}
#[doc = "DMA Controller 0"]
pub mod dma0;
#[doc = "DMA1 instance"]
pub type Dma1 = crate::Periph<dma0::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for Dma1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma1").finish()
    }
}
#[doc = "DMA1 instance"]
pub use self::dma0 as dma1;
#[doc = "Security algorithm engine"]
pub type Sae = crate::Periph<sae::RegisterBlock, 0x4003_2000>;
impl core::fmt::Debug for Sae {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sae").finish()
    }
}
#[doc = "Security algorithm engine"]
pub mod sae;
#[doc = "Hardware random-number generator"]
pub type Rng = crate::Periph<rng::RegisterBlock, 0x4003_3000>;
impl core::fmt::Debug for Rng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rng").finish()
    }
}
#[doc = "Hardware random-number generator"]
pub mod rng;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "RCC"]
    pub rcc: Rcc,
    #[doc = "SYSCFG"]
    pub syscfg: Syscfg,
    #[doc = "PWR"]
    pub pwr: Pwr,
    #[doc = "I2S"]
    pub i2s: I2s,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "LPUART"]
    pub lpuart: Lpuart,
    #[doc = "SSP0"]
    pub ssp0: Ssp0,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "AFEC"]
    pub afec: Afec,
    #[doc = "LORAC"]
    pub lorac: Lorac,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "TIMER2"]
    pub timer2: Timer2,
    #[doc = "BSTIMER0"]
    pub bstimer0: Bstimer0,
    #[doc = "LPTIMER0"]
    pub lptimer0: Lptimer0,
    #[doc = "LPTIMER1"]
    pub lptimer1: Lptimer1,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SEC"]
    pub sec: Sec,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "UART3"]
    pub uart3: Uart3,
    #[doc = "SSP1"]
    pub ssp1: Ssp1,
    #[doc = "SSP2"]
    pub ssp2: Ssp2,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "LCD"]
    pub lcd: Lcd,
    #[doc = "DAC"]
    pub dac: Dac,
    #[doc = "TIMER1"]
    pub timer1: Timer1,
    #[doc = "TIMER3"]
    pub timer3: Timer3,
    #[doc = "BSTIMER1"]
    pub bstimer1: Bstimer1,
    #[doc = "IWDG"]
    pub iwdg: Iwdg,
    #[doc = "WDG"]
    pub wdg: Wdg,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "GPIOD"]
    pub gpiod: Gpiod,
    #[doc = "EFC"]
    pub efc: Efc,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "DMA0"]
    pub dma0: Dma0,
    #[doc = "DMA1"]
    pub dma1: Dma1,
    #[doc = "SAE"]
    pub sae: Sae,
    #[doc = "RNG"]
    pub rng: Rng,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            rcc: Rcc::steal(),
            syscfg: Syscfg::steal(),
            pwr: Pwr::steal(),
            i2s: I2s::steal(),
            uart0: Uart0::steal(),
            uart1: Uart1::steal(),
            lpuart: Lpuart::steal(),
            ssp0: Ssp0::steal(),
            i2c0: I2c0::steal(),
            afec: Afec::steal(),
            lorac: Lorac::steal(),
            timer0: Timer0::steal(),
            timer2: Timer2::steal(),
            bstimer0: Bstimer0::steal(),
            lptimer0: Lptimer0::steal(),
            lptimer1: Lptimer1::steal(),
            rtc: Rtc::steal(),
            sec: Sec::steal(),
            uart2: Uart2::steal(),
            uart3: Uart3::steal(),
            ssp1: Ssp1::steal(),
            ssp2: Ssp2::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            adc: Adc::steal(),
            lcd: Lcd::steal(),
            dac: Dac::steal(),
            timer1: Timer1::steal(),
            timer3: Timer3::steal(),
            bstimer1: Bstimer1::steal(),
            iwdg: Iwdg::steal(),
            wdg: Wdg::steal(),
            gpioa: Gpioa::steal(),
            gpiob: Gpiob::steal(),
            gpioc: Gpioc::steal(),
            gpiod: Gpiod::steal(),
            efc: Efc::steal(),
            crc: Crc::steal(),
            dma0: Dma0::steal(),
            dma1: Dma1::steal(),
            sae: Sae::steal(),
            rng: Rng::steal(),
        }
    }
}
